server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

spring:
  application:
    name: fraud
  datasource:
    username: mushtaq
    password: ushallpass
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true